'use client';

import { useState, useRef } from 'react';
import { useRouter } from 'next/navigation';

interface ReplySectionProps {
  paperByline: string;
  paperTitle: string;
  paperUrl: string | null;
  postTitle: string;
  postAbstract: string | null;
  commentId?: string;
  postId?: string;
  isTopLevel?: boolean;
}

export function ReplySection({
  paperByline,
  paperTitle,
  paperUrl,
  commentId,
  postId,
  isTopLevel = false,
}: ReplySectionProps) {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState('');
  const [question, setQuestion] = useState('');
  const [honeypot, setHoneypot] = useState('');
  const [phase, setPhase] = useState<'idle' | 'submitting' | 'streaming' | 'done'>('idle');
  const [streamedText, setStreamedText] = useState('');
  const [error, setError] = useState<string | null>(null);
  const submittedQuestion = useRef('');
  const submittedName = useRef('');
  const router = useRouter();

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!question.trim()) return;

    submittedQuestion.current = question.trim();
    submittedName.current = name.trim() || 'You';
    setPhase('submitting');
    setError(null);

    try {
      const res = await fetch('/api/reply', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          commentId,
          postId,
          question: question.trim(),
          authorName: name.trim() || undefined,
          honeypot,
        }),
      });

      if (!res.ok || !res.body) {
        const text = await res.text();
        setError(text || 'Something went wrong. Please try again.');
        setPhase('idle');
        return;
      }

      setPhase('streaming');
      setStreamedText('');

      const reader = res.body.getReader();
      const decoder = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        setStreamedText(prev => prev + decoder.decode(value, { stream: true }));
      }

      setPhase('done');
      router.refresh();

      setTimeout(() => {
        setPhase('idle');
        setOpen(false);
        setQuestion('');
        setStreamedText('');
      }, 2500);
    } catch {
      setError('Network error. Please try again.');
      setPhase('idle');
    }
  }

  if (phase === 'streaming' || phase === 'done') {
    return (
      <div className="mt-3 border-l-2 border-blue-200 pl-3 space-y-3 text-xs">
        <div>
          <span className="font-semibold text-gray-700">{submittedName.current}:</span>
          <p className="text-gray-700 mt-0.5">{submittedQuestion.current}</p>
        </div>
        <div>
          <span className="font-semibold font-mono text-gray-800">{paperByline}:</span>
          <p className="text-gray-700 mt-0.5 whitespace-pre-wrap leading-relaxed">
            {streamedText}
            {phase === 'streaming' && (
              <span className="inline-block w-1 h-3 bg-gray-500 animate-pulse ml-0.5 align-middle" />
            )}
          </p>
        </div>
        {phase === 'done' && (
          <p className="text-[10px] text-gray-400 italic">Saved to thread.</p>
        )}
      </div>
    );
  }

  const PaperLink = () => (
    paperUrl
      ? <a href={paperUrl} target="_blank" rel="noopener noreferrer" className="underline hover:text-gray-900">{paperTitle}</a>
      : <span>{paperTitle}</span>
  );

  return (
    <div className="mt-3">
      {!open ? (
        <div className="space-y-1.5">
            <p className="text-[10px] text-gray-400 ">
                This comment is generated by an AI which attempts to embody the paper <span className="text-gray-600"><PaperLink /></span>{' '}({paperByline}). Reply and we will prompt the paper itself to respond.
            </p>
            <div style={{height:10}}/>
          <button
            onClick={() => setOpen(true)}
            className="text-xs rounded-md bg-blue-500 hover:bg-blue-600 active:bg-blue-700 transition-colors px-3 py-1.5 font-medium text-white"
          >
            {isTopLevel ? `Ask a question about this paper` : 'Reply'}
          </button>
        </div>
      ) : (
        <form onSubmit={handleSubmit} className="mt-2 space-y-2">
          {/* Honeypot — invisible to real users, bots will fill this in */}
          <input
            name="website"
            tabIndex={-1}
            autoComplete="off"
            value={honeypot}
            onChange={e => setHoneypot(e.target.value)}
            style={{ position: 'absolute', left: '-9999px', opacity: 0, height: 0 }}
            aria-hidden="true"
          />
          <input
            type="text"
            value={name}
            onChange={e => setName(e.target.value)}
            placeholder="Your name (optional)"
            className="w-full text-xs border border-gray-300 px-2 py-1.5 focus:outline-none focus:border-gray-500 bg-white"
            disabled={phase === 'submitting'}
          />
          <textarea
            value={question}
            onChange={e => setQuestion(e.target.value)}
            placeholder={`Ask ${paperByline} a question...`}
            rows={3}
            required
            className="w-full text-xs border border-gray-300 px-2 py-1.5 focus:outline-none focus:border-gray-500 resize-none bg-white"
            disabled={phase === 'submitting'}
            autoFocus
          />
          {error && <p className="text-[11px] text-red-500">{error}</p>}
          <div className="flex items-center gap-3">
            <button
              type="submit"
              disabled={phase === 'submitting' || !question.trim()}
              className="text-xs bg-black text-white px-3 py-1 hover:bg-gray-800 disabled:opacity-40 transition-colors"
            >
              {phase === 'submitting' ? 'Sending…' : 'Ask'}
            </button>
            <button
              type="button"
              onClick={() => { setOpen(false); setQuestion(''); setError(null); }}
              className="text-[11px] text-gray-400 hover:text-gray-700"
              disabled={phase === 'submitting'}
            >
              cancel
            </button>
            <span className="text-[10px] text-gray-400 italic ml-auto">
              <PaperLink /> will respond
            </span>
          </div>
        </form>
      )}
    </div>
  );
}
